version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: base64:EKXh9ASiYS2mHEj6HNFR2lhJjeuPGhuIfm4YNOvpDgo=
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: todo_db
            DB_USERNAME: todo_user
            DB_PASSWORD: todo_pass
            MAIL_MAILER: smtp
            MAIL_HOST: live.smtp.mailtrap.io
            MAIL_PORT: 587
            MAIL_ENCRYPTION: tls
            MAIL_USERNAME: api
            MAIL_PASSWORD: e108c62bc506a22e134c323e65f0862e
            MAIL_FROM_ADDRESS: hello@demomailtrap.co
            MAIL_FROM_NAME: "TaskPlanner"

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: todo_db
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: todo_pass
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    dbdata:
